/* ============================================================
   Quiz data for the ECN 11A Quiz Hub.
   Each module maps to course content (readings / lectures).
   Module 1 ships with the full "Colonial Economy — Labor Force"
   video-lecture question bank, transcribed verbatim.
   ============================================================ */

function mkQuestions(list) {
  return list.map((item, index) => ({
    id: "q" + (index + 1),
    question: item[0],
    options: item[1],
    correct: item[2],
    explanation: item[3]
  }));
}

const COLONIAL_ECONOMY_QUESTIONS = mkQuestions([
  ["During the first few years of colonization, death rates were:",
    ["Extremely low", "Initially very high", "Identical to England's throughout the period", "Irrelevant to population growth"],
    1, "Death rates were initially very high during the first settlement years."],
  ["After the initial settlement period, colonial death rates:",
    ["Continued increasing", "Fell significantly", "Remained above 50 per thousand", "Became impossible to estimate"],
    1, "They fell significantly after the initial period."],
  ["In the eighteenth-century British North American colonies, the death rate was approximately:",
    ["5–10 per thousand annually", "10–15 per thousand annually", "20–25 per thousand annually", "40–50 per thousand annually"],
    2, "Approximately 20–25 deaths per thousand annually."],
  ["In eighteenth-century England, the death rate was approximately:",
    ["5–15 per thousand annually", "15–20 per thousand annually", "20–25 per thousand annually", "25–35 per thousand annually"],
    3, "England was approximately 25–35 per thousand."],
  ["Compared with England, death rates in the British North American colonies were generally:",
    ["Higher", "Lower", "Exactly equal", "Unrelated to living conditions"],
    1, "Colonial rates were lower than England's."],
  ["Which factor best explains the colonies' relatively low death rates?",
    ["Superior colonial medical technology", "Warmer winters than England", "Plentiful food, fuel, and land per person", "The complete absence of infectious disease"],
    2, "Food, fuel, housing, and land per person improved resistance to disease."],
  ["Why could plentiful food and housing reduce colonial death rates?",
    ["Colonists never encountered disease", "Well-fed and well-housed people could withstand disease more successfully", "Colonists were genetically immune to European diseases", "Food eliminated the need for medical care"],
    1, "Nutrition and shelter made people more capable of surviving illness."],
  ["Which apparent puzzle does the lecture emphasize?",
    ["Colonies had better hospitals but higher death rates", "Colonies had harsh winters and inferior medical technology but relatively low death rates", "England had more land but less food", "Immigration stopped immediately after Jamestown"],
    1, "Low mortality existed despite harsh weather and inferior medicine."],
  ["Early in the colonial period, the primary source of labor-force growth was:",
    ["Technological innovation", "Immigration", "Falling wages", "Retirement reform"],
    1, "Immigration drove early workforce growth."],
  ["Later in the colonial period, the main source of labor-force growth was:",
    ["Continued dependence on immigration alone", "Natural population growth", "A fall in birth rates", "Increasing Native American migration"],
    1, "Natural increase became dominant later."],
  ["Natural population growth in the colonies resulted primarily from:",
    ["Low birth rates and high death rates", "High birth rates and low death rates", "High immigration and low wages", "Low immigration and high mortality"],
    1, "High births plus low deaths generate natural population growth."],
  ["On the eve of the American Revolution, approximately what share of free colonists was foreign-born?",
    ["One in ten", "Three in ten", "Five in ten", "Nine in ten"],
    0, "About one in ten free colonists was foreign-born."],
  ["On the eve of the Revolution, approximately what share of free colonists was born in the colonies?",
    ["One in ten", "Two in ten", "Five in ten", "Nine in ten"],
    3, "About nine in ten were colonial-born."],
  ["On the eve of the Revolution, approximately what share of enslaved workers living in the colonies was foreign-born?",
    ["None", "One in twenty", "Two or three in ten", "Nine in ten"],
    2, "Approximately two or three in ten enslaved workers were foreign-born."],
  ["The population evidence from the eve of the Revolution most strongly supports which conclusion?",
    ["Population growth still depended almost entirely on newly arriving Europeans", "Natural increase had become the main source of population and workforce growth", "Colonial birth rates had collapsed", "Almost all free colonists had been born in England"],
    1, "The large colonial-born share indicates natural increase had become dominant."],
  ["The Native American population in the eastern area of what became the United States was approximately how large near the beginning of settlement?",
    ["30,000", "100,000", "300,000", "3 million"],
    2, "Approximately 300,000."],
  ["By the eve of the Revolution, this Native American population had fallen to:",
    ["Slightly below 300,000", "Less than 100,000", "Exactly 200,000", "More than 500,000"],
    1, "The population fell below 100,000."],
  ["According to the lecture, the main cause of this population decline was:",
    ["Inferior agricultural technology", "Voluntary migration to Europe", "European diseases", "Falling colonial wages"],
    2, "European diseases were the principal cause identified."],
  ["Why were European diseases especially destructive to Native American communities?",
    ["Native Americans had no previous immunity to many of the diseases", "Native Americans had stopped producing food", "European diseases only affected agricultural workers", "Native Americans had superior immunity but insufficient land"],
    0, "The population lacked immunity to many introduced diseases."],
  ["Which sequence best summarizes the colonial population story?",
    ["Natural increase first, immigration later", "Immigration first, natural increase later", "Falling population first, no growth later", "Technological growth first, population decline later"],
    1, "Immigration first; natural growth later."],

  ["Indentured servitude in the British colonies began early in the settlement of:",
    ["Boston", "Jamestown", "New York", "Philadelphia"],
    1, "The lecture connects early indenture with Jamestown."],
  ["By approximately 1775, more than how many of the roughly 500,000 immigrants had financed migration using an indenture contract?",
    ["50,000", "150,000", "250,000", "350,000"],
    3, "More than 350,000 of approximately 500,000 immigrants."],
  ["Under a typical indenture arrangement, who initially paid the worker's passage?",
    ["The colonial government", "The worker's future children", "The shipper", "The English monarch"],
    2, "The shipper financed passage."],
  ["What did the worker provide in exchange for the shipper paying the passage?",
    ["Permanent ownership of the worker's land", "A contract promising labor for a set period", "A percentage of the worker's future taxes", "Military service to England"],
    1, "The worker promised labor for a specified term."],
  ["After arriving in North America, the shipper normally:",
    ["Employed every servant personally", "Destroyed the contract", "Sold the contract to a merchant or planter", "Returned the worker to England"],
    2, "The shipper sold the contract after arrival."],
  ["What did the merchant or planter purchase from the shipper?",
    ["Ownership of the worker for life", "The indenture contract and right to the worker's labor during its term", "The worker's British citizenship", "The worker's family property"],
    1, "The purchaser obtained contractual labor rights for the specified period."],
  ["When the contractual term was completed, the indentured worker:",
    ["Automatically became enslaved", "Was returned to the shipper", "Was free to leave", "Had to sign another identical contract"],
    2, "The worker became free after fulfilling the contract."],
  ["A servant working for a merchant might have a term of approximately:",
    ["One year", "Three years", "Five years", "Fifteen years"],
    2, "A merchant arrangement might last about five years."],
  ["A servant working for a planter might have a term of approximately:",
    ["Three years", "Seven years", "Ten years", "Twenty years"],
    0, "A planter arrangement might last about three years."],
  ["Contract length could vary according to:",
    ["Only the worker's religion", "Skills, physical strength, and type of work", "Only the distance from London", "The size of the English population"],
    1, "Terms varied with skills, strength, and work requirements."],
  ["The approximate cost of passage discussed in the lecture was:",
    ["Less than one penny", "Approximately five pounds sterling", "Approximately fifty pounds sterling", "Approximately five hundred pounds sterling"],
    1, "Approximately five pounds sterling."],
  ["Why was this passage cost difficult for many migrants to pay?",
    ["It equaled or exceeded approximately one year of per-capita income in England", "English law prohibited workers from using savings", "The colonies accepted only gold", "Workers had to purchase colonial land before traveling"],
    0, "This was approximately equal to or greater than annual per-capita income."],
  ["What underlying market problem did indentured servitude help solve?",
    ["An excess supply of ships", "A lack of labor mobility caused by workers' inability to finance passage", "A shortage of land in England", "An inability of colonial employers to write contracts"],
    1, "Workers lacked funds even though employers wanted their labor."],
  ["The indenture system \"greased the wheels of the labor market\" because it:",
    ["Eliminated the need for workers", "Connected workers who wanted to migrate with colonial employers demanding labor", "Prevented contracts from being transferred", "Required all migrants to own ships"],
    1, "The arrangement connected labor supply and labor demand."],
  ["Which sequence correctly describes the transaction?",
    ["Planter pays worker → worker buys a ship → shipper signs contract", "Worker signs with shipper → shipper transports worker → planter buys contract", "Worker buys contract → planter travels to England → shipper works in colony", "Government transports worker → contract is permanently cancelled"],
    1, "Sign contract, travel, then contract sale."],
  ["The shipper's average additional return from transporting an indentured servant was approximately:",
    ["1–2 percent", "5–7 percent", "11–15 percent", "40–50 percent"],
    2, "Approximately 11–15 percent additional return."],
  ["What was one reason offered for the shipper's additional return?",
    ["Transporting servants was completely risk-free", "The shipper faced risks such as sickness, death during the voyage, or escape after arrival", "Indentured servants always paid twice", "The colonial government guaranteed every contract"],
    1, "The shipper bore sickness, mortality, and escape risks."],
  ["Which statement best reflects the lecture's treatment of fairness?",
    ["Everyone agrees indenture was completely fair", "Everyone agrees indenture was completely exploitative", "There is debate about fairness, but broad agreement that it increased labor mobility", "Economic historians refuse to study fairness"],
    2, "Fairness is debated; its mobility effect is broadly accepted."],
  ["If an indentured worker died during the voyage, the shipper could:",
    ["Still sell the completed labor contract for its full value", "Lose the expected revenue from selling the contract", "Require the planter to purchase another worker", "Recover the loss automatically from the government"],
    1, "A death could eliminate the contract's sale value."],
  ["Which participant acted as the financial intermediary in the indenture system?",
    ["The Native American population", "The shipping company", "The colonial church", "The English army"],
    1, "The shipper performed the financing/intermediary role."],

  ["Indentured servants were primarily:",
    ["Elderly women", "Young men", "Retired landowners", "Young children"],
    1, "Indentured servants were disproportionately male."],
  ["Their typical age was:",
    ["Under ten", "Late teens or early twenties", "Forties or fifties", "Over seventy"],
    1, "They were commonly in their late teens or early twenties."],
  ["Why was their age considered economically important?",
    ["They were at or near the peak of their productive ability", "They had already retired", "They required no food or housing", "They could not perform agricultural work"],
    0, "They arrived near peak productive age."],
  ["According to the lecture's argument, England had borne much of the cost of:",
    ["Employing the servants after arrival", "Feeding and housing them while they were children", "Purchasing colonial farms", "Training every servant as a merchant"],
    1, "England had incurred much of their childhood consumption cost."],
  ["The colonies received these workers primarily when they were:",
    ["Too young to work", "Ready to work productively", "Already retired", "Unable to perform physical labor"],
    1, "They entered the colonies ready to work."],
  ["Why was the disproportionately male composition considered advantageous in the lecture's historical setting?",
    ["The colonial economy was mainly agrarian and relied heavily on physical labor", "Women were legally forbidden from entering the colonies", "Men had lower literacy", "Agricultural work required no strength"],
    0, "Physical strength was valuable in the agrarian economy."],
  ["Compared with the general English population, indentured servants were described as:",
    ["Less likely to be literate", "Approximately equally literate in every case", "Relatively more literate on average", "Completely illiterate"],
    2, "They were relatively literate compared with England's general population."],
  ["Literacy could increase colonial productivity because it was useful:",
    ["Only for religious ceremonies", "In trades and even in agricultural activity", "Only for returning to England", "Only for military service"],
    1, "Literacy aided trades and agricultural work."],
  ["Which combination best captures the lecture's productivity argument?",
    ["Old, weak, illiterate, and permanently dependent", "Young, strong, disproportionately male, and relatively literate", "Wealthy, elderly, urban, and retired", "Young, unskilled, unwilling to work, and landless"],
    1, "This is the complete characteristic set emphasized."],
  ["Which is the best economic interpretation of the colonies receiving workers in their late teens or early twenties?",
    ["The colonies paid all childhood-rearing costs but received little labor", "England incurred much of their childhood cost, while the colonies received them during productive years", "The servants generated no output after arrival", "Their age had no relationship to productivity"],
    1, "England bore early costs; the colonies received productive labor."],

  ["One reason indentured servitude declined was that passage:",
    ["Became more expensive", "Became less expensive", "Was legally prohibited", "Could only be paid by planters"],
    1, "Passage costs declined."],
  ["Lower passage costs reduced indenture because:",
    ["More migrants could pay their own transportation costs", "Workers became less productive", "Planters stopped demanding labor", "England stopped producing ships"],
    0, "More migrants could self-finance."],
  ["Why did passage become less expensive according to the lecture?",
    ["Ships became more efficient and more ships were available", "Ocean distances became shorter", "Workers stopped eating during voyages", "Colonial governments banned transportation charges"],
    0, "Shipping efficiency and availability improved."],
  ["Rising wages in England reduced indentured migration because:",
    ["English workers had less ability to pay passage", "Migrants could increasingly pay their own way or had less reason to leave", "Colonial wages automatically fell to zero", "Servants became less literate"],
    1, "Workers could pay or had less incentive to leave England."],
  ["An increase in English wages would reduce the wage advantage of migrating when:",
    ["The difference between earnings in England and the colonies became smaller", "Colonial wages increased infinitely", "English workers became enslaved", "Shipping costs became irrelevant"],
    0, "The earnings advantage of migration narrowed."],
  ["Established families in the colonies contributed to the decline of indenture by:",
    ["Preventing relatives from migrating", "Paying the passage of cousins, nieces, nephews, and other relatives", "Increasing the length of every indenture", "Prohibiting migrants from using family money"],
    1, "Families financed additional relatives."],
  ["A final factor in indenture's decline was that:",
    ["Enslaved labor became relatively less expensive", "Enslaved labor became impossible to obtain", "Free labor disappeared", "Agricultural labor was no longer needed"],
    0, "Enslaved labor became relatively less costly."],
  ["Which answer provides the most complete explanation for indenture's decline?",
    ["One single law immediately abolished it", "Passage became cheaper, English wages increased, colonial families financed relatives, and enslaved labor became cheaper", "All European migration ended", "Colonial employers stopped caring about labor costs"],
    1, "The lecture presents multiple simultaneous factors."],
  ["Which explanation is least consistent with the lecture?",
    ["Improved shipping allowed more people to self-finance", "Higher English wages made indenturing less attractive", "Family assistance reduced the financing problem", "A sharp decline in English wages made indenture disappear"],
    3, "Falling English wages would generally make indenturing more attractive."],
  ["The professor uses indentured servitude's decline to demonstrate how economic historians:",
    ["Select one cause without consulting evidence", "Build a model and compare its predictions with historical data", "Avoid quantitative reasoning", "Assume institutions never respond to prices"],
    1, "The case illustrates model construction and empirical testing."],

  ["In the labor-supply graph, the vertical axis represents:",
    ["Quantity of land", "Wage or price of labor", "Number of ships", "Agricultural output"],
    1, "Wage is the price of labor and belongs on the vertical axis."],
  ["The horizontal axis represents:",
    ["Quantity of labor", "Wage rates", "Passage cost only", "English population only"],
    0, "Quantity of labor belongs on the horizontal axis."],
  ["The model identifies how many major sources of colonial labor?",
    ["One", "Two", "Three", "Five"],
    2, "Free, indentured, and enslaved labor."],
  ["The three labor sources are:",
    ["Agricultural, industrial, and governmental workers", "Free workers, indentured Europeans, and enslaved workers", "English, French, and Spanish workers", "Men, women, and children"],
    1, "Those are the model's three categories."],
  ["In the lecture's simplified model, free labor supply is:",
    ["Perfectly elastic", "Completely inelastic", "Downward-sloping", "Absent below W2"],
    1, "Free labor is simplified as completely inelastic."],
  ["A completely inelastic supply curve is drawn as:",
    ["A horizontal line", "A vertical line", "A downward-sloping line", "A circle"],
    1, "Perfectly inelastic supply is vertical."],
  ["Why is free labor modeled as completely inelastic?",
    ["Workers had a strong social safety net", "A fixed group had to work regardless of the wage because not working meant not eating", "Free workers could be imported without limit", "Their wages were legally fixed at zero"],
    1, "With no safety net, the existing workers must work."],
  ["In this context, \"free labor\" means:",
    ["Labor that costs employers nothing", "Workers who are not enslaved", "Workers who receive no wage", "Government workers"],
    1, "\"Free\" means not enslaved, not zero cost."],
  ["W1 represents:",
    ["The highest wage paid to enslaved workers", "The lowest wage at which the first European is willing to indenture", "The cost of colonial land", "England's death rate"],
    1, "W1 is the minimum wage threshold for indenturing."],
  ["The indentured-labor supply curve begins at:",
    ["A wage of zero", "W1", "W2 only", "The quantity of free labor"],
    1, "Indentured supply starts at W1."],
  ["Below W1, Europeans are:",
    ["Willing to indenture in unlimited numbers", "Not willing to indenture under the assumptions of the model", "Automatically enslaved", "Already part of free colonial labor"],
    1, "The wage is insufficient to attract indentured Europeans."],
  ["W2 represents:",
    ["The wage paid directly to an enslaved worker", "The cost of transporting and enslaving a worker", "The average English wage", "The passage price for every free colonist"],
    1, "W2 is the cost of obtaining enslaved labor."],
  ["The enslaved-labor supply curve is modeled as:",
    ["Perfectly elastic at W2", "Perfectly inelastic at W2", "Downward-sloping from W1", "Identical to free labor supply"],
    0, "The model treats enslaved supply as horizontal at W2."],
  ["A perfectly elastic supply curve is drawn as:",
    ["A vertical line", "A horizontal line", "An upward-sloping line", "A downward-sloping line"],
    1, "Perfectly elastic supply is horizontal."],
  ["Why does the curve appear at W2 even though enslaved workers were not paid W2 as wages?",
    ["W2 represents the employer's acquisition and transportation cost", "W2 represents a voluntary wage accepted by enslaved workers", "W2 represents their income after emancipation", "W2 represents the cost of colonial land"],
    0, "W2 is an employer cost, not a wage voluntarily received."],
  ["At W2, the simplified model assumes:",
    ["No enslaved labor can be obtained", "A highly elastic or indefinite supply of enslaved labor is available", "Only free workers remain", "All indentured workers return to England"],
    1, "An indefinite amount is modeled as available at that cost."],
  ["Assuming W1 is below W2, which labor is available at a wage below W1?",
    ["Free labor only", "Indentured labor only", "Enslaved labor only", "Indentured and enslaved labor only"],
    0, "Before W1, only the existing free workforce is available."],
  ["Assuming W1 is below W2, which additional labor source begins to enter when wages reach W1?",
    ["Free labor", "Indentured labor", "Enslaved labor", "Military labor"],
    1, "Indentured labor begins at W1."],
  ["Assuming W1 is below W2, which additional source becomes available when labor costs reach W2?",
    ["Only free workers", "Enslaved labor", "English landowners", "Native American land"],
    1, "Enslaved labor becomes available at W2."],
  ["At a wage below W2, employers would generally prefer:",
    ["More costly enslaved labor regardless of price", "Free or indentured workers already available at lower cost", "To stop producing entirely", "To raise W2 voluntarily"],
    1, "Below W2, less-costly available labor is preferred."],

  ["Early in the colonial period, W2 was relatively:",
    ["Low because shipping was free", "High because transatlantic transportation was expensive", "Equal to zero", "Unrelated to transportation costs"],
    1, "High shipping costs produced a high W2."],
  ["Early in the colonial period, W1 was relatively:",
    ["Low", "High", "Infinite", "Equal to W2 by definition"],
    0, "W1 was relatively low early."],
  ["Why was W1 relatively low early in the period?",
    ["Wages in England were relatively low, making migration more attractive", "English wages were much higher than colonial wages", "Every worker had family financing", "Passage was free"],
    0, "Low English wages increased willingness to migrate."],
  ["The lack of established colonial relatives early in the period tended to:",
    ["Eliminate the need for financing", "Increase migrants' reliance on indenture contracts", "Make enslaved labor free", "Shift W2 downward"],
    1, "Without family financing, contracts were more necessary."],
  ["The coexistence of indentured and enslaved labor early in the period suggests that labor demand was:",
    ["Always below W1", "Sufficiently high for both forms to appear", "Equal to zero", "Located entirely to the left of free labor supply"],
    1, "Demand had to be high enough for both categories to appear."],
  ["If labor demand had been extremely far to the left, the model predicts the economy might use:",
    ["Only free labor", "Only indentured labor", "Only enslaved labor", "No labor of any kind"],
    0, "Very low demand could be satisfied by the fixed free workforce."],
  ["Toward the end of the colonial period, falling shipping costs caused W2 to:",
    ["Increase", "Decrease", "Remain mechanically fixed", "Become equal to English wages"],
    1, "Lower transportation costs reduced W2."],
  ["Graphically, a decrease in W2 shifts the enslaved-labor supply curve:",
    ["Up", "Down", "Vertically to the right", "Into a downward-sloping curve"],
    1, "The horizontal W2 line shifts downward."],
  ["Rising English wages caused W1 to:",
    ["Fall", "Rise", "Become zero", "Become the colonial death rate"],
    1, "Better English opportunities raised the required colonial incentive."],
  ["Family assistance with passage caused potential migrants to require:",
    ["A greater incentive before accepting indenture", "No income from colonial work", "A lower W2", "Permanent enslavement"],
    0, "Workers with alternatives require more compensation to accept indenture."],
  ["Graphically, an increase in W1 shifts the relevant portion of the indentured-labor supply curve:",
    ["Down", "Up", "Into a horizontal line at zero", "To the origin"],
    1, "The indenture threshold shifts upward."],
  ["Late in the period, which combination occurred?",
    ["W1 fell and W2 rose", "W1 rose and W2 fell", "Both W1 and W2 rose equally", "Both disappeared"],
    1, "This is the central late-period change."],
  ["If W2 falls below W1, what happens before wages can rise sufficiently to attract indentured servants?",
    ["Enslaved labor becomes available at the lower cost W2", "All free workers leave", "Labor demand disappears", "W1 automatically falls to zero"],
    0, "Enslaved supply enters at the lower threshold."],
  ["Why can indentured servants disappear when W2 is below W1?",
    ["The elastic supply of enslaved labor at W2 prevents the market labor cost from reaching W1", "Free labor becomes illegal", "England prohibits migration", "The indentured supply curve becomes vertical"],
    0, "The elastic supply at W2 holds labor cost below W1."],
  ["Which graph best represents the lecture's late-colonial story?",
    ["W1 shifts down and W2 shifts up", "W1 shifts up and W2 shifts down", "Both curves remain unchanged despite new evidence", "Free labor becomes perfectly elastic"],
    1, "Upward W1 and downward W2."],
  ["The decline of indenture is therefore explained as:",
    ["A random event unrelated to costs", "A response to changing relative prices and migration opportunities", "Proof that labor demand vanished", "Proof that all European workers became wealthy"],
    1, "The institution responded to changing relative costs."],
  ["Which change would make indentured labor more likely to remain important?",
    ["A low W1 combined with a high W2", "A high W1 combined with a low W2", "A fall in English-colony wage differences", "Extensive family financing of passage"],
    0, "Cheap indenture and costly enslavement favor indentured labor."],
  ["Which change would make enslaved labor relatively more attractive to employers?",
    ["A rise in W2", "A fall in W2", "A fall in colonial labor demand to zero", "A rise in the cost of transportation from Africa"],
    1, "A lower W2 reduces the employer's cost."],
  ["Which change would make Europeans more willing to sign indenture contracts?",
    ["A reduction in W1", "An increase in W1", "A reduction in W2 only", "A vertical shift in free labor supply"],
    0, "A lower threshold means more Europeans are willing to indenture."],
  ["The professor cautions that this diagram is:",
    ["A precise, complete aggregate labor-supply curve", "A simplified or \"hand-wavy\" representation used to convey the general mechanism", "A model of the English money supply", "A calculation of exact colonial wages"],
    1, "The professor calls it a simplified, intuitive representation."],

  ["The labor-supply explanation is an example of cliometrics because it:",
    ["Uses only personal opinions about the past", "Combines an economic model with historical data and statistical evidence", "Rejects economic theory", "Assumes all historical institutions are identical"],
    1, "Cliometrics combines economics, models, and historical evidence."],
  ["What historical observation is the model designed to explain?",
    ["Indentured servitude was absent early but dominant late", "Indentured servitude was important early but largely absent late", "Free labor never existed", "Shipping costs continually rose"],
    1, "The institution was significant early and largely absent later."],
  ["What is the correct first step in the lecture's economic-history method?",
    ["Decide the conclusion and ignore conflicting evidence", "Identify the historical pattern that needs explanation", "Use a modern example without studying history", "Assume only one cause is possible"],
    1, "Begin with the historical pattern."],
  ["After identifying possible causes, economic historians should:",
    ["Construct a model whose predictions can be compared with data", "Memorize the causes without evaluating them", "Eliminate economic intuition", "Avoid distinguishing between W1 and W2"],
    0, "Construct a testable economic explanation."],
  ["Which observation supports the model's explanation?",
    ["Shipping costs rose and English wages fell", "Shipping costs fell, English wages rose, families financed passage, and indenture declined", "Indenture increased as W1 moved above W2", "Enslaved labor became more costly while indenture disappeared"],
    1, "Those changes match the predicted movements in W1 and W2."],
  ["Which statement best demonstrates synthesis rather than simple memorization?",
    ["\"W1 is W1.\"", "\"Higher English wages raised the minimum incentive needed to accept indenture, shifting W1 upward.\"", "\"The lecture mentioned wages.\"", "\"Indenture existed because history is complicated.\""],
    1, "It explains the mechanism rather than repeating a label."],

  ["Max Weber is associated with an argument linking:",
    ["Protestantism and capitalism", "Mercantilism and Native American immunity", "Shipping and death rates", "Catholicism and indenture contracts"],
    0, "Weber linked Protestant culture with capitalist development."],
  ["According to this interpretation, Protestant religious culture emphasized:",
    ["Avoiding all economic activity", "Work, land acquisition, property, and material success", "Permanent poverty as the only moral outcome", "Returning all colonial land to England"],
    1, "Work, land, property, and material success were emphasized."],
  ["The economic significance of these beliefs was that they could:",
    ["Reduce the desire to work", "Encourage productivity, accumulation, and investment", "Eliminate agricultural production", "Raise death rates"],
    1, "These values could promote productive behavior."],
  ["Cotton Mather's teaching, as presented in the lecture, suggested that colonists could:",
    ["Trust in God for success in their daily business", "Engage in no commercial activity", "Become moral only by abandoning property", "Avoid productive work"],
    0, "Mather presented business success as consistent with religious faith."],
  ["The lecture contrasts Mather's message with doctrines emphasizing:",
    ["Immediate accumulation and business success", "Present sacrifice and reward in the afterlife", "The purchase of indenture contracts", "Low colonial death rates"],
    1, "The contrast was with present sacrifice for later reward."],
  ["Timothy Dwight's statement connected sound morals with:",
    ["Hatred of property", "A certain degree of love of property", "Complete rejection of earthly concerns", "Permanent dependence on England"],
    1, "Dwight connected some love of property with sound morals."],
  ["In Weber's interpretation, the religious community or social network:",
    ["Reinforced motivations to work and acquire property", "Prohibited economic cooperation", "Prevented investment", "Eliminated literacy"],
    0, "Social networks reinforced the productive values."],
  ["Which behavior would be most consistent with the religious doctrine discussed?",
    ["Avoiding all investment because earthly concerns are immoral", "Working hard, improving property, and viewing business success positively", "Refusing to acquire land", "Reducing output deliberately"],
    1, "Hard work and property improvement fit the argument."],
  ["According to the lecture, this religious culture might have made the colonial labor force:",
    ["Less productive than Europe's", "Especially productive", "Entirely dependent on government", "Unable to engage in agriculture"],
    1, "The doctrine was offered as one explanation for high productivity."],
  ["Which answer most accurately presents the Weber argument?",
    ["Every Protestant was necessarily more productive than every non-Protestant", "Religious and social values may have reinforced behaviors favorable to capitalist productivity", "Religion was the only cause of colonial economic performance", "Protestantism caused lower shipping costs directly"],
    1, "It is a cultural-incentive argument, not a universal claim about individuals."],

  ["A new shipping technology sharply lowers the cost of transporting enslaved workers across the Atlantic. In the model, the most direct effect is:",
    ["W1 shifts upward", "W1 shifts downward", "W2 shifts downward", "Free labor becomes horizontal"],
    2, "Cheaper transportation of enslaved labor lowers W2."],
  ["Wages in England rise until workers can earn nearly as much there as in the colonies. The most likely effect is:",
    ["W1 rises", "W1 falls", "W2 rises", "Free labor disappears"],
    0, "Better English opportunities raise W1."],
  ["Established colonists begin paying the migration costs of their European relatives. The most likely effect is:",
    ["More workers must use indenture contracts", "Fewer workers need to indenture themselves", "W2 rises sharply", "Colonial death rates increase"],
    1, "Family financing removes the need to sell future labor."],
  ["Suppose English wages fall dramatically while colonial wages remain high. Other things equal, Europeans would likely:",
    ["Require a higher colonial wage before indenturing", "Be willing to indenture at a lower wage", "Stop migrating entirely", "Increase W2"],
    1, "Poorer English opportunities make migration attractive at a lower wage."],
  ["Suppose shipping from Africa becomes more expensive. The model predicts:",
    ["W2 rises", "W2 falls", "W1 necessarily falls", "Free labor becomes perfectly elastic"],
    0, "More expensive acquisition raises W2."],
  ["Suppose W1 is $8 and W2 is $15. At a colonial wage of $10, which labor sources would be active under the simplified model?",
    ["Free labor only", "Free and indentured labor", "Free and enslaved labor", "Enslaved labor only"],
    1, "$10 exceeds W1 but remains below W2."],
  ["Suppose W1 is $18 and W2 is $12. Why might indentured labor be absent?",
    ["Enslaved labor becomes available before the wage reaches the indenture threshold", "Free workers refuse all employment", "Employers must pay enslaved workers $18", "W2 automatically increases to $18"],
    0, "Enslaved supply becomes available at $12, before wages reach $18."],
  ["Suppose the labor demand curve intersects labor supply below W1. Which workforce would the model predict?",
    ["Free workers only", "Indentured workers only", "Enslaved workers only", "Indentured and enslaved workers only"],
    0, "Demand is satisfied by the fixed free workforce."],
  ["Suppose labor demand rises from below W1 to a level above W1 but below W2, assuming W1 < W2. What happens?",
    ["Indentured labor enters the workforce", "Enslaved labor enters first", "Free labor disappears", "W1 falls to zero"],
    0, "Crossing W1 brings indentured workers into the market."],
  ["A historian observes that indenture declined at the same time that shipping improved and English earnings increased. The historian builds a labor-supply model and tests it against migration records. This is:",
    ["Mercantilism", "Cliometrics", "Natural increase", "Path independence"],
    1, "This is a direct example of cliometrics."],
  ["A news article describes modern migrants borrowing from intermediaries to finance transportation and then working under contract to repay the debt. Which colonial concept is most directly comparable?",
    ["Natural population growth", "Indentured servitude as a financing and labor-mobility mechanism", "Perfectly inelastic free labor", "The Protestant work ethic"],
    1, "Both use future labor to finance migration."],
  ["In the preceding modern example, what is the most important economic question?",
    ["Whether financing allows workers to move to places where their labor is demanded", "Whether all migration is identical", "Whether workers are young men", "Whether Native American death rates changed"],
    0, "The key issue is whether financing overcomes a mobility barrier."],
  ["A colony has abundant food, fuel, and housing but relatively primitive medicine. Which prediction is most consistent with the lecture?",
    ["Mortality must be higher than England's", "Better nutrition and shelter may still produce relatively low mortality", "Medicine is the only determinant of death rates", "Natural growth becomes impossible"],
    1, "Food and shelter can offset disadvantages in medicine and climate."],
  ["A population grows rapidly even though immigration has slowed. Which evidence would best explain this?",
    ["High birth rates combined with low death rates", "High death rates combined with low births", "Rising W2", "Declining literacy"],
    0, "That is natural population growth."],
  ["A student says, \"Colonial population growth was caused by immigration.\" What is missing from this answer?",
    ["Immigration was unimportant at every point", "The source changed over time, with natural increase becoming dominant later", "All population growth came from enslaved migration", "The Native American population increased"],
    1, "The dominant mechanism changed over time."],
  ["Which answer best tells the complete economic story of indenture's decline?",
    ["\"Indenture simply became unpopular.\"", "\"Conditions raised W1 while falling transportation costs lowered W2, so enslaved labor became available before wages reached the threshold needed to attract indentured Europeans.\"", "\"The number of free workers became zero.\"", "\"Religious dissenters prohibited contracts.\""],
    1, "This answer supplies both the curve movements and resulting outcome."],
  ["Which piece of evidence would most strongly challenge the lecture's model?",
    ["English wages rose while indenture declined", "Shipping costs fell while enslaved labor became cheaper", "W1 fell substantially, W2 rose substantially, yet indentured servitude disappeared", "Colonial families increasingly financed relatives"],
    2, "Those movements predict the opposite result."],
  ["Which piece of evidence would most strongly support the Weber interpretation?",
    ["Religious communities praised hard work, property improvement, and successful business activity", "Religious communities discouraged all productive activity", "Colonists prohibited private property", "Literacy fell to zero"],
    0, "It directly demonstrates social reinforcement of productive values."],
  ["An exam prompt asks you to graph the end of indentured servitude. Which labels are essential?",
    ["Price level, real GDP, aggregate demand", "Wage, quantity of labor, W1, W2, and the three sources of labor", "Interest rate and money supply only", "Birth rate and death rate only"],
    1, "Those labels are necessary to communicate the labor model."],
  ["After drawing the early and late labor-market graphs, the most important written explanation would be:",
    ["Only that the lines moved", "Why economic changes caused W1 to rise, W2 to fall, and indenture to disappear", "The exact artistic color of each curve", "A calculation of colonial GDP"],
    1, "The professor prioritizes the economic intuition behind the graph."]
]);

const DEFAULT_MODULES = [
  {
    id: "module-1",
    name: "Module 1",
    description: "Colonial economy and the early American labor force.",
    quizzes: [
      {
        id: "m1-colonial-economy-labor-force",
        title: "Colonial Economy — Labor Force",
        type: "Video Lecture",
        source: "",
        scoringGuide: [
          { min: 123, max: 136, label: "Excellent command; begin practicing written graph explanations." },
          { min: 109, max: 122, label: "Strong, but review curve shifts and application questions." },
          { min: 90, max: 108, label: "Basic knowledge is present; strengthen causal mechanisms." },
          { min: 0, max: 89, label: "Rewatch the lecture while handwriting the sequence: population → indenture → productivity → W1/W2 shifts → disappearance of indenture → Weber." }
        ],
        questions: COLONIAL_ECONOMY_QUESTIONS
      }
    ]
  },
  { id: "module-2", name: "Module 2", description: "", quizzes: [] },
  { id: "module-3", name: "Module 3", description: "", quizzes: [] },
  { id: "module-4", name: "Module 4", description: "", quizzes: [] },
  { id: "module-5", name: "Module 5", description: "", quizzes: [] },
  { id: "module-6", name: "Module 6", description: "", quizzes: [] }
];

const QUIZ_TYPES = ["Video Lecture", "Reading", "Lecture Notes", "Podcast", "Case Study", "Discussion", "Other"];
